export const TIERS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    priceInPaise: 0,
    maxPhotos: 50,
    maxSelected: 20,
    galleryDurationDays: 7,
    watermark: true,
    customSlug: false,
    guestUploads: false,
    faceFilter: false,
    passwordProtect: false,
    maxEvents: 1,
    description: 'Try MemoryLane with one event',
    cta: 'Create free gallery',
    popular: false,
  },
  basic: {
    id: 'basic',
    name: 'Basic',
    price: 499,
    priceInPaise: 49900,
    maxPhotos: 500,
    maxSelected: 80,
    galleryDurationDays: 365,
    watermark: false,
    customSlug: true,
    guestUploads: false,
    faceFilter: true,
    passwordProtect: false,
    maxEvents: 1,
    description: 'One event, beautifully shared',
    cta: 'Create gallery — ₹499',
    popular: false,
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    price: 999,
    priceInPaise: 99900,
    maxPhotos: 2000,
    maxSelected: 200,
    galleryDurationDays: null,  // never expires
    watermark: false,
    customSlug: true,
    guestUploads: true,
    faceFilter: true,
    passwordProtect: true,
    maxEvents: 3,
    description: 'Up to 3 events, all the features',
    cta: 'Get Premium — ₹999',
    popular: true,
  },
  photographer: {
    id: 'photographer',
    name: 'Photographer',
    price: 1999,
    priceInPaise: 199900,
    billingCycle: 'monthly',
    maxPhotos: 5000,
    maxSelected: 500,
    galleryDurationDays: null,
    watermark: false,
    customSlug: true,
    guestUploads: true,
    faceFilter: true,
    passwordProtect: true,
    maxEvents: null,  // unlimited
    clientBranding: true,
    priorityProcessing: true,
    description: 'Unlimited events for professional photographers',
    cta: 'Start free trial — then ₹1,999/month',
    popular: false,
  }
} as const

export type TierId = keyof typeof TIERS
